name: 'Dependency Review'

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          deny-licenses: AGPL-1.0-or-later, LGPL-2.0-or-later
          
      - name: Python Dependency Check
        run: |
          pip install safety
          safety check -r requirements.txt
          
      - name: Node.js Dependency Check
        run: |
          cd frontend
          npm audit 